<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?> 
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/light-theme.css') ?>
</head>
<body>
	<div class="site-wrapper">
		<div class="header"><a class="homepage" href="<?php echo $this->ServerUrl() . $this->BaseUrl(); ?>">Home</a></div>

<div id="content">
    <h1>
    	<?php echo $this->escape($this->title); ?>
    </h1>
    <?php echo $this->layout()->content; ?>

</div>
</div>
</body>
</html>